### ISSUE TITLE
Relationship as FamilyMemberHistory vs Observation

### ISSUE THREAD

**Issue by liberaliscomputing** [ga4gh-cp/pedigree-fhir-ig#2]
@ametke derived [Pedigree Relationship](https://ga4gh-cp.github.io/pedigree-fhir-ig/StructureDefinition-PedigreeRelationship.html) from [FamilyMemberHistory](http://hl7.org/fhir/R4/familymemberhistory.html) while @liberaliscomputing built [Relationship](https://liberaliscomputing.github.io/pedigree-fhir-ig/StructureDefinition-relationship.html) off of [Observation](http://hl7.org/fhir/R4/observation.html). Let's discuss pros and cons of these approaches in modeling [Relationship](https://github.com/ga4gh-cp/pedigree/blob/master/model.md#relationship).

**Comment by ametke** [comment]
Hi @liberaliscomputing. I think this is the main difference between our implementations. My decision to use [FamilyMemberHistory](http://hl7.org/fhir/R4/familymemberhistory.html) rather than [Observation](http://hl7.org/fhir/R4/observation.html) was based on the advice found on the FHIR specification (my emphasis):

> At its core, Observation allows expressing a name-value pair or structured collection of name-value pairs. As such, it can support conveying any type of information desired. However, that is not its intent. Observation is intended for capturing measurements and subjective point-in-time assessments. **It is not intended to be used for those specific contexts and use cases already covered by other FHIR resources.** For example, the AllergyIntolerance resource represents a patient allergies, MedicationStatement resource: medications taken by a patient, **FamilyMemberHistory resource: a patient's family history**, Procedure resource: information about a procedure, and QuestionnaireResponse resource: a set of answers to a set of questions.

**Comment by liberaliscomputing** [comment]
@ametke, I see your rationale. Why I considered Observation as more relevant for representing a family relationship than FamilyMemberHistory was two-fold:

1. Observation's Scope and Usage

> Observations are a central element in healthcare, used to support diagnosis, monitor progress, determine baselines and patterns and **even capture demographic characteristics**.

As quoted and in bold above, capturing demographic characteristics is one of the intended use for Observation. Though whether a family relationship can be considered as a demographic characteristic remains questionable.

2. Observation's Independency from Use of Extension

As we agreed in #1, I prefer not to use an Extension(s) when not necessary. While FamilyMemberHistory is supposed to curate a family history, I've questioned the followings:

- FamilyMemberHistory, by default, misses a `subject` attribute. Without using either an Extension(s) or other bundling resources (such as List or Composition), it cannot associate `patient` with other people;
- A family relationship doesn't seem like a family "history"; and
- FamilyMemberHistory is supposed to capture a family member **when considered under a specific Condition**. This consideration is not a meta-essence of familial relationship. So, when decoupled from Condition, would the use of FamilyMemberHistory still be in the intended scope?

In contrast, Observation already has `subject` and `focus`, and `value[x]` can be used to represent a type of relationship. In addition, due to the above reasons, it seems to me that the family relationship use case is not already covered by FamilyMemberHistory.

BUT, HL7 already uses it for the [Genetic Pedigree](http://hl7.org/fhir/R4/familymemberhistory-genetic.html) profile, so my thoughts might've been mistaken :)

**Comment by ametke** [comment]
Hi @liberaliscomputing. I agree with your first point in the sense that an observation _could_ be used to represent the relationship. The question really is if the existing specific resource can also be used for this purpose, because in that case the spec does tell you that you should not use an observation. As you point out, my decision was mostly based on the fact that the genetic pedigree had already profiled that resource.

Regarding your second point, I do indeed use an extension but it is an official HL7 extension and thus it is well known, and therefore doesn't negatively impact interoperability in the same way as a new extension would.

**Comment by RobertJCarroll** [comment]
From FamilyMedicalHistory: "This resource records significant health conditions for a particular individual related to the subject." The key piece (included in @ametke 's emphasis above) is their **history** not the **relationship**. I don't believe FamilyMedicalHistory is intended to represent the relationships among Patients, as that's not a common model in EHRs. I agree it's a non-specific use of Observation, but that seems reasonable vs using the FamilyMedicalHistory for an out-of-scope use case.

**Comment by fiendish** [comment]
> A family relationship doesn't seem like a family "history"

> The key piece (included in @ametke 's emphasis above) is their history not the relationship.

I agree with both @liberaliscomputing and @RobertJCarroll. "family history" means predispositions not relationships, so the bolded proscription against using Observation in https://github.com/ga4gh-cp/pedigree-fhir-ig/issues/2#issuecomment-819233591 wouldn't apply here. Being related to someone is not a health condition nor is it contextual to care as FamilyMedicalHistory is defined to be.

Side note: I also think it's probably bad for https://ga4gh-cp.github.io/pedigree-fhir-ig/StructureDefinition-PedigreeRelationship.html to mandate nonzero cardinality of an external identifier for something descriptive like a relationship that generally won't have one.

**Comment by ametke** [comment]
@fiendish, I agree with the nonzero cardinality. I originally added the cardinality restriction because the relationship id in the concept model was `required` but after checking the documentation this is meant to be an internal identifier so I will remove this restriction.

**Comment by ametke** [comment]
Based on the discussion on today's call (see [here](https://docs.google.com/document/d/12gw2BBIPVaWxUNQx2qiVVIt7W0zVOHON_2Ts9yc9fWY/edit)), we will implement this approach for now and revisit this decision later.
