### ISSUE TITLE
FSH Resources Organization

### ISSUE THREAD

**Issue by liberaliscomputing** [ga4gh-cp/pedigree-fhir-ig#3]
FSH is an emerging technology in the FHIR community and has been rapidly growing. In contrast to the maturity of conventions in vanilla FHIR resources development, there has been less discussion about the organization of FSH resources. Let's discuss pros and cons of a variety of approaches in organizing FSH resources.

**Comment by liberaliscomputing** [comment]
One option can be to follow how SUSHI, the most widely accepted compiler for FSH, organizes FSH resources.

Upon resource validation (`sushi .`), the compiler summarizes the validation results as follows:

```
╔════════════════════════ SUSHI RESULTS ══════════════════════════╗
║ ╭──────────┬────────────┬───────────┬─────────────┬───────────╮ ║
║ │ Profiles │ Extensions │ ValueSets │ CodeSystems │ Instances │ ║
║ ├──────────┼────────────┼───────────┼─────────────┼───────────┤ ║
║ │    5     │     0      │     2     │      1      │    20     │ ║
║ ╰──────────┴────────────┴───────────┴─────────────┴───────────╯ ║
║                                                                 ║
╠═════════════════════════════════════════════════════════════════╣
║ That went swimmingly!                  0 Errors      0 Warnings ║
╚═════════════════════════════════════════════════════════════════╝
```

As shown above, SUSHI groups FSH resources into five categories: 1) Profile, 2) Extension, 3) ValueSet, 4) CodeSystem, and 5) Instance. We can adopt this categorization when naming and organizing FSH resources, considering the object-oriented programming convention. For example, based on camel-casing, we can name the Patient profile FSH resource as `Profile-Patient.fsh` while putting all of the examples of Patient into `Instance-Patient.fsh`. When we create a custom profile off of Patient, say Individual, we can name this resource `Profile-Individual.fsh` since the object-oriented programming conventionally put parent and child classes into separate files. The NIH Cloud Platform Interoperability Effort (NCPI) FHIR IG Working Group also employs this organization: https://github.com/ncpi-fhir/ncpi-fhir-ig/tree/main/input/fsh

**Comment by ametke** [comment]
Hi @liberaliscomputing. I think this is a great idea and happy to update the FSH definitions to follow this pattern. The only one I am not so sure about is instances. I think it would make more sense to keep the examples contained within a single FSH file. For example, there are two simple examples in the IG at the moment and we will add at least three more complex ones from the connectathon. If we follow this approach then we would have to look at multiple files to find all the instances related to a single example, rather than easily finding all of the related instances in a single file.

What if we follow the proposed conventions for profiles, extensions, value sets and code systems and for examples we follow a similar convention but grouped by example, e.g. `Example-Simpsons.fsh'?

**Comment by liberaliscomputing** [comment]
@ametke, I am glad we agree to agree! Yeah, bundling related instances into one FSH file makes more sense. Otherwise, we would need to look into multiple files in order to make updates to one set of examples. 

Then, how about bundling related examples like `Instance-Simpsons.fsh` and `Instance-Pedigree-1.fsh` while keeping more general, independent examples under `Instance-[ResourceType].fsh`?

**Comment by ametke** [comment]
@liberaliscomputing, yes, I think we can keep more general, independent examples under `Instance-[ResourceType].fsh`. I would prefer to name the full examples differently though. What if we use `Example-[ExampleName].fsh` for these? That way it is easy to tell if the files are full examples or independent example instances.

**Comment by liberaliscomputing** [comment]
@ametke, that sounds like a plan!

**Comment by liberaliscomputing** [comment]
@ametke, feel free to push the new FSH resources organization commit directly to the main branch. If you want me to review, then tag me in your PR!

**Comment by ametke** [comment]
Thanks @liberaliscomputing! I've pushed the changes now.
